jwt:
  secret: japanhiroshimanagasakifatmanandlittleboyjapanhiroshimanagasakifatmanandlittleboyjapanhiroshimanagasakifatmanandlittleboyjapanhiroshimanagasakifatmanandlittleboy

cloud:
    key: 332461697253746
    secret: a27KPVQEQoTJERaCg-KWgZbs7lI
    name: dhxi8e1gb